CREATE TABLE IF NOT EXISTS recruiters (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  company VARCHAR(255),
  title VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  link VARCHAR(500),
  company VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS h1b_sponsors (
  id SERIAL PRIMARY KEY,
  company VARCHAR(255) UNIQUE NOT NULL,
  is_sponsor BOOLEAN NOT NULL,
  source VARCHAR(255),
  checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);